name: Manual Build Windows Wheel
on: workflow_dispatch # 手动触发

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install CUDA
        uses: jimmy-p/setup-cuda@v2.1.0
        with:
          cuda_version: '12.1.1' # 这里填你 ComfyUI 用的 CUDA 版本
      - name: Build
        run: |
          pip install wheel setuptools torch==2.7.0 --index-url https://download.pytorch.org/whl/cu121
          python setup.py bdist_wheel
      - uses: actions/upload-artifact@v4
        with:
          name: nunchaku-1.1.0-win
          path: dist/*.whl
